var dureMASTERList = 
{
	"GAVI": [
{"code":"AFG", "name":"AFGHANISTAN"},
{"code":"AGO", "name":"ANGOLA"},
{"code":"ARM", "name":"ARMENIA"},
{"code":"AZE", "name":"AZERBAIJAN"},
{"code":"BGD", "name":"BANGLADESH"},
{"code":"BEN", "name":"BENIN"},
{"code":"BTN", "name":"BHUTAN"},
{"code":"BOL", "name":"BOLIVIA"},
{"code":"BFA", "name":"BURKINA FASO"},
{"code":"BDI", "name":"BURUNDI"},
{"code":"KHM", "name":"CAMBODIA"},
{"code":"CMR", "name":"CAMEROON"},
{"code":"CAF", "name":"CENTRAL AFRICAN REPUBLIC"},
{"code":"TCD", "name":"CHAD"},
{"code":"COM", "name":"COMOROS"},
{"code":"COG", "name":"CONGO"},
{"code":"COD", "name":"CONGO, THE DEMOCRATIC REPUBLIC OF THE"},
{"code":"CIV", "name":"CÔTE D'IVOIRE"},
{"code":"CUB", "name":"CUBA"},
{"code":"DJI", "name":"DJIBOUTI"},
{"code":"ERI", "name":"ERITREA"},
{"code":"ETH", "name":"ETHIOPIA"},
{"code":"GMB", "name":"GAMBIA"},
{"code":"GEO", "name":"GEORGIA"},
{"code":"GHA", "name":"GHANA"},
{"code":"GIN", "name":"GUINEA"},
{"code":"GNB", "name":"GUINEA-BISSAU"},
{"code":"GUY", "name":"GUYANA"},
{"code":"HTI", "name":"HAITI"},
{"code":"HND", "name":"HONDURAS"},
{"code":"IND", "name":"INDIA"},
{"code":"IDN", "name":"INDONESIA"},
{"code":"KEN", "name":"KENYA"},
{"code":"KIR", "name":"KIRIBATI"},
{"code":"PRK", "name":"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"},
{"code":"KGZ", "name":"KYRGYZSTAN"},
{"code":"LAO", "name":"LAO PEOPLE'S DEMOCRATIC REPUBLIC"},
{"code":"LSO", "name":"LESOTHO"},
{"code":"LBR", "name":"LIBERIA"},
{"code":"MDG", "name":"MADAGASCAR"},
{"code":"MWI", "name":"MALAWI"},
{"code":"MLI", "name":"MALI"},
{"code":"MRT", "name":"MAURITANIA"},
{"code":"MDA", "name":"MOLDOVA, REPUBLIC OF"},
{"code":"MNG", "name":"MONGOLIA"},
{"code":"MOZ", "name":"MOZAMBIQUE"},
{"code":"MMR", "name":"MYANMAR"},
{"code":"NPL", "name":"NEPAL"},
{"code":"NIC", "name":"NICARAGUA"},
{"code":"NER", "name":"NIGER"},
{"code":"NGA", "name":"NIGERIA"},
{"code":"PAK", "name":"PAKISTAN"},
{"code":"PNG", "name":"PAPUA NEW GUINEA"},
{"code":"RWA", "name":"RWANDA"},
{"code":"STP", "name":"SAO TOME AND PRINCIPE"},
{"code":"SEN", "name":"SENEGAL"},
{"code":"SLE", "name":"SIERRA LEONE"},
{"code":"SLB", "name":"SOLOMON ISLANDS"},
{"code":"SOM", "name":"SOMALIA"},
{"code":"LKA", "name":"SRI LANKA"},
{"code":"SDN", "name":"SUDAN"},
{"code":"SSD", "name":"SUDAN, REPUBLIC OF SOUTH"},
{"code":"TJK", "name":"TAJIKISTAN"},
{"code":"TZA", "name":"TANZANIA, UNITED REPUBLIC OF"},
{"code":"TLS", "name":"TIMOR-LESTE"},
{"code":"TGO", "name":"TOGO"},
{"code":"UGA", "name":"UGANDA"},
{"code":"UKR", "name":"UKRAINE"},
{"code":"UZB", "name":"UZBEKISTAN"},
{"code":"VNM", "name":"VIET NAM"},
{"code":"YEM", "name":"YEMEN"},
{"code":"ZMB", "name":"ZAMBIA"},
{"code":"ZWE", "name":"ZIMBABWE"}

      ],

	"NON-GAVI": [
{"code":"ALB", "name":"ALBANIA"},
{"code":"DZA", "name":"ALGERIA"},
{"code":"AND", "name":"ANDORRA"},
{"code":"ATG", "name":"ANTIGUA AND BARBUDA"},
{"code":"ARG", "name":"ARGENTINA"},
{"code":"AUS", "name":"AUSTRALIA"},
{"code":"AUT", "name":"AUSTRIA"},
{"code":"BHS", "name":"BAHAMAS"},
{"code":"BHR", "name":"BAHRAIN"},
{"code":"BRB", "name":"BARBADOS"},
{"code":"BLR", "name":"BELARUS"},
{"code":"BEL", "name":"BELGIUM"},
{"code":"BLZ", "name":"BELIZE"},
{"code":"BIH", "name":"BOSNIA AND HERZEGOVINA"},
{"code":"BWA", "name":"BOTSWANA"},
{"code":"BRA", "name":"BRAZIL"},
{"code":"BRN", "name":"BRUNEI DARUSSALAM"},
{"code":"BGR", "name":"BULGARIA"},
{"code":"CAN", "name":"CANADA"},
{"code":"CPV", "name":"CAPE VERDE"},
{"code":"CHL", "name":"CHILE"},
{"code":"CHN", "name":"CHINA"},
{"code":"COL", "name":"COLOMBIA"},
{"code":"COK", "name":"COOK ISLANDS"},
{"code":"CRI", "name":"COSTA RICA"},
{"code":"HRV", "name":"CROATIA"},
{"code":"CYP", "name":"CYPRUS"},
{"code":"CZE", "name":"CZECH REPUBLIC"},
{"code":"DNK", "name":"DENMARK"},
{"code":"DMA", "name":"DOMINICA"},
{"code":"DOM", "name":"DOMINICAN REPUBLIC"},
{"code":"ECU", "name":"ECUADOR"},
{"code":"EGY", "name":"EGYPT"},
{"code":"SLV", "name":"EL SALVADOR"},
{"code":"GNQ", "name":"EQUATORIAL GUINEA"},
{"code":"EST", "name":"ESTONIA"},
{"code":"FJI", "name":"FIJI"},
{"code":"FIN", "name":"FINLAND"},
{"code":"FRA", "name":"FRANCE"},
{"code":"GAB", "name":"GABON"},
{"code":"DEU", "name":"GERMANY"},
{"code":"GRC", "name":"GREECE"},
{"code":"GRD", "name":"GRENADA"},
{"code":"GTM", "name":"GUATEMALA"},
{"code":"HUN", "name":"HUNGARY"},
{"code":"ISL", "name":"ICELAND"},
{"code":"IRN", "name":"IRAN, ISLAMIC REPUBLIC OF"},
{"code":"IRQ", "name":"IRAQ"},
{"code":"IRL", "name":"IRELAND"},
{"code":"ISR", "name":"ISRAEL"},
{"code":"ITA", "name":"ITALY"},
{"code":"JAM", "name":"JAMAICA"},
{"code":"JPN", "name":"JAPAN"},
{"code":"JOR", "name":"JORDAN"},
{"code":"KAZ", "name":"KAZAKHSTAN"},
{"code":"KOR", "name":"KOREA, REPUBLIC OF"},
{"code":"KWT", "name":"KUWAIT"},
{"code":"LVA", "name":"LATVIA"},
{"code":"LBN", "name":"LEBANON"},
{"code":"LBY", "name":"LIBYAN ARAB JAMAHIRIYA"},
{"code":"LTU", "name":"LITHUANIA"},
{"code":"LUX", "name":"LUXEMBOURG"},
{"code":"MKD", "name":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"},
{"code":"MYS", "name":"MALAYSIA"},
{"code":"MDV", "name":"MALDIVES"},
{"code":"MLT", "name":"MALTA"},
{"code":"MHL", "name":"MARSHALL ISLANDS"},
{"code":"MUS", "name":"MAURITIUS"},
{"code":"MEX", "name":"MEXICO"},
{"code":"FSM", "name":"MICRONESIA, FEDERATED STATES OF"},
{"code":"MCO", "name":"MONACO"},
{"code":"MNE", "name":"MONTENEGRO"},
{"code":"MAR", "name":"MOROCCO"},
{"code":"NAM", "name":"NAMIBIA"},
{"code":"NRU", "name":"NAURU"},
{"code":"NLD", "name":"NETHERLANDS"},
{"code":"NZL", "name":"NEW ZEALAND"},
{"code":"NIU", "name":"NIUE"},
{"code":"NOR", "name":"NORWAY"},
{"code":"OMN", "name":"OMAN"},
{"code":"PLW", "name":"PALAU"},
{"code":"PAN", "name":"PANAMA"},
{"code":"PRY", "name":"PARAGUAY"},
{"code":"PER", "name":"PERU"},
{"code":"PHL", "name":"PHILIPPINES"},
{"code":"POL", "name":"POLAND"},
{"code":"PRT", "name":"PORTUGAL"},
{"code":"QAT", "name":"QATAR"},
{"code":"ROU", "name":"ROMANIA"},
{"code":"RUS", "name":"RUSSIAN FEDERATION"},
{"code":"KNA", "name":"SAINT KITTS AND NEVIS"},
{"code":"LCA", "name":"SAINT LUCIA"},
{"code":"VCT", "name":"SAINT VINCENT AND THE GRENADINES"},
{"code":"WSM", "name":"SAMOA"},
{"code":"SMR", "name":"SAN MARINO"},
{"code":"SAU", "name":"SAUDI ARABIA"},
{"code":"SRB", "name":"SERBIA"},
{"code":"SYC", "name":"SEYCHELLES"},
{"code":"SGP", "name":"SINGAPORE"},
{"code":"SVK", "name":"SLOVAKIA"},
{"code":"SVN", "name":"SLOVENIA"},
{"code":"ZAF", "name":"SOUTH AFRICA"},
{"code":"ESP", "name":"SPAIN"},
{"code":"SUR", "name":"SURINAME"},
{"code":"SWZ", "name":"SWAZILAND"},
{"code":"SWE", "name":"SWEDEN"},
{"code":"CHE", "name":"SWITZERLAND"},
{"code":"SYR", "name":"SYRIAN ARAB REPUBLIC"},
{"code":"THA", "name":"THAILAND"},
{"code":"TON", "name":"TONGA"},
{"code":"TTO", "name":"TRINIDAD AND TOBAGO"},
{"code":"TUN", "name":"TUNISIA"},
{"code":"TUR", "name":"TURKEY"},
{"code":"TKM", "name":"TURKMENISTAN"},
{"code":"TUV", "name":"TUVALU"},
{"code":"ARE", "name":"UNITED ARAB EMIRATES"},
{"code":"GBR", "name":"UNITED KINGDOM"},
{"code":"USA", "name":"UNITED STATES"},
{"code":"URY", "name":"URUGUAY"},
{"code":"VUT", "name":"VANUATU"},
{"code":"VEN", "name":"VENEZUELA"}
	]
};

